# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "d1bcaff842fafd2a052130aa8f459e55"
name = "test-buildapp"
handle = "test-buildapp"
application_url = "https://firefox-virtual-execute-trick.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "starting-to-build-app.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://firefox-virtual-execute-trick.trycloudflare.com/auth/callback",
  "https://firefox-virtual-execute-trick.trycloudflare.com/auth/shopify/callback",
  "https://firefox-virtual-execute-trick.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
